version: '3.1'

services:

  db:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_PASSWORD: man
      POSTGRES_DB: restapi
    ports:
    - 5432:5432

  cache:
    image: redis:3.2.4
    ports:
    - "6379:6379"

