version: '3.1'

services:

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - 5432:5432

  redis:
    image: redis:3.2.4
    ports:
    - "6379:6379"

  nats:
    image: nats:1.3.0
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

